### ISSUE TITLE
No need to implement Bearer auth

### ISSUE THREAD

**Issue by shadowhand** [multidimension-al/oauth2-shopify#3]
The provider says [it uses Bearer auth](https://github.com/multidimension-al/oauth2-shopify/blob/89a9d86a2263ca63c84493c8febac63a2e6594e9/src/Provider/Shopify.php#L14) and then [overloads the method `BearerAuthorizationTrait` provides](https://github.com/multidimension-al/oauth2-shopify/blob/89a9d86a2263ca63c84493c8febac63a2e6594e9/src/Provider/Shopify.php#L97).

There is no need for the provider to use `BearerAuthorizationTrait` if a custom auth scheme is used.

**Comment by ajquick** [comment]
Hopefully that fixes both issues #3 and #4.
