### ISSUE TITLE
Use array accessor for resource owner

### ISSUE THREAD

**Issue by shadowhand** [multidimension-al/oauth2-shopify#4]
The [`ArrayAccessorTrait`](https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/ArrayAccessorTrait.php) can be used in the resource owner class to ensure that undefined index errors are avoided if the accessed keys are not available.

**Comment by ajquick** [comment]
Hopefully that fixes both issues #3 and #4.

**Comment by ajquick** [comment]
Fixed in 42732d3
